language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

script:
  - cd trac/1.2.2
  - image="anyshpm/trac:1.2.2"
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"
  - cd ../../socks5/3.8.9
  - image="anyshpm/socks5:3.8.9"
  - docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images
